# Generated by Django 3.1.7 on 2021-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event/static/EventImages/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='event/static/VenueImages/'),
        ),
    ]
